fixed issue GEOS-9825
geoserver/geoserver pull request #4636
Opened 2021-01-01 19:49 UTC by robinhoutmeyers

This fix advertises GetMap POST support in the WMS 1.3.0 capabilities, which allows WMS clients to automatically discover POST as one of the supported HTTP request methods.  Geoserver does support GetMap POST for an older WMS GetMap XML Schema; by means of https://osgeo-org.atlassian.net/browse/GEOS-9823, it will also support the SLD 1.1 WMS GetMap XML Schema from http://schemas.opengis.net/sld/1.1/GetMap.xsd.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

2021-01-01 21:20 UTC, mprins requested changes
QA run failed with "Found 7 non-complying files" please run the formatter before committing, as described in https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md#commit-guidelines

also a great deal of tests are failing and there are public API changes, such as removing class `GetMapXmlReader`

2021-01-11 14:37 UTC, aaime reviewed
Besides the comments about the code, could you also update the documentation (as per our check-list) mentioning an example of the WMS 1.3 GetMap?

Here is a page that talks about the issue:
https://github.com/geoserver/geoserver/blob/master/doc/en/user/source/services/wms/reference.rst

2021-01-11 14:37 UTC, aaime commented on src/wms/src/test/java/org/geoserver/wms/map/GetMapOwsXmlReaderTest.java
> +package org.geoserver.wms.map;
Lacks copyright header

2021-01-11 14:37 UTC, aaime commented on src/wms/src/main/java/org/geoserver/wms/map/GetMapOwsXmlReader.java
> +package org.geoserver.wms.map;
Lacks copyright header

2021-01-11 14:37 UTC, aaime commented on src/wms/src/main/java/org/geoserver/wms/map/GetMapSldXmlReader.java
> +package org.geoserver.wms.map;
Lacks copyright header

2021-01-11 14:37 UTC, aaime commented on src/wms/src/test/java/org/geoserver/wms/map/GetMapSldXmlReaderTest.java
> +package org.geoserver.wms.map;
Lacks copyright header

2021-01-11 14:37 UTC, aaime commented on src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesAllowedRequestTypesTest.java
> +public class CapabilitiesAllowedRequestTypesTest extends WMSTestSupport {
Running tests in GeoServer is slow due to the expensive setup, please do not create a new test class for a single test, merge in an existing test with a similar topic instead. This seems like a good candidate:
https://github.com/geoserver/geoserver/blob/772e58a2d3bbba009f3ab980c2171c31f6bf3f9f/src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

2021-01-11 14:37 UTC, aaime commented on src/wms/src/main/java/org/geoserver/wms/map/GetMapSldXmlReader.java
> +public class GetMapSldXmlReader extends AbstractGetMapXmlReader {
This seems incorrect. The schema is part of the SLD 1.1 specification, so I'm assuming it's referring to a SLD 1.1 sld:StyledLayerDescriptor. However, the SLD parser used in the base class can only parse SLD 1.0.
The parsing of SLD 1.1 documents is present, but it's a whole different beast, e.g.:
https://github.com/geoserver/geoserver/blob/e701004e988a8d0a9b7d993090c9a96dcf155e12/src/main/src/main/java/org/geoserver/catalog/SLDHandler.java#L196

2021-02-01 10:01 UTC, aaime commented
Is this PR still alive? Feedback was provided some 20 days ago, it's up to the PR submitter to update the code so that is passes review.

2021-02-01 10:39 UTC, robinhoutmeyers commented
Yes, I am still planning to update it based on the received feedback; I haven't found the time yet but I hope to address the listed comments soon.

2021-02-16 18:34 UTC, jodygarnett commented
We are looking at PRs for upcoming release candidate March 1st, do you think this can be ready in time?

2021-02-18 11:35 UTC, robinhoutmeyers commented
Hi Jody, this will unfortunately be difficult due to timing issues at my side; if ok, I would like to wrap this up during Q2.

2021-02-25 11:25 UTC, aaime commented
Wrapping in Q2 sounds fine, I'll set a not to check back this PR in June then.

2021-06-16 01:55 UTC, closed without merging