[GEOS-9984] ColorMap labels in raster layer GetFeatureInfo response
geoserver/geoserver pull request #4886
Opened 2021-03-19 13:33 UTC by taba90

This pr 

- adds the possibility to include in the GetFeatureInfo output for raster layer the ColorMapEntry label if any in the Style being request.

- is blocked by https://github.com/geotools/geotools/pull/3404

- Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9984

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

2021-03-22 16:01 UTC, aaime requested changes

2021-03-23 09:31 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +The default output for a ``GetFeatureInfo`` request over a raster layer, comprises just the value of the selected pixel for each band of the image.
fixed

2021-03-23 09:31 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +If the raster layer is served with a Style having a ``ColorMap``, GeoServer provides the possibility to include in the output the label of the ``ColorMapEntry`` matching the pixel value, thanks to a
fixed

2021-03-23 09:31 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +With the example ``RasterSymbolizer`` we will obtain something like:
fixed

2021-03-23 09:32 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +        <sld:ColorMapEntry color="#FFFF00" quantity="124.81173566700335" label="label is 124.811736"/>
fixed

2021-03-23 09:32 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +* ``none`` no label is added to the output. We obtain a normal ``GetFeaturInfo`` response.
fixed

2021-03-23 09:32 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +        <sld:ColorMapEntry color="#0000FF" quantity="1.0" label="label is 1"/>
fixed

2021-03-23 10:01 UTC, taba90 commented on doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
> +We have been using the ``JSON`` output format for the example above, but the two ``VendorOptions`` work also with ``HTML`` output.
fixed

2021-03-23 10:01 UTC, taba90 commented on src/wms/src/main/java/org/geoserver/wms/featureinfo/LabelInFeatureInfo.java
> +class LabelInFeatureInfo {
fixed

2021-03-23 10:01 UTC, taba90 commented on src/wms/src/main/java/org/geoserver/wms/featureinfo/LabelInFeatureInfo.java
> +class LabelInFeatureInfo {
I've added tests for this class and the visitor

2021-03-23 10:01 UTC, taba90 commented on src/wms/src/main/java/org/geoserver/wms/featureinfo/LabelInFeatureInfo.java
> +                ColorMapEntry prev = entries[i - 1];
fixed

2021-03-23 10:01 UTC, taba90 commented on src/wms/src/main/java/org/geoserver/wms/featureinfo/LabelInFeatureInfo.java
> +        return label;
fixed

2021-03-23 10:02 UTC, taba90 commented on src/wms/src/main/java/org/geoserver/wms/featureinfo/LabelInFeatureInfo.java
> +        return label;
in case of a type interval the colorMap is not going to style pixel with values > the last entry quantity

2021-03-23 10:04 UTC, taba90 commented on src/wms/src/main/java/org/geoserver/wms/featureinfo/LabelInFeatureInfo.java
> +        return Long.valueOf(
indeed it was suppose to be a filtering step not a map one. It has been fixed, I've also modified a test sld with two entries to cover properly the use case where this methods turns out to be needed. https://github.com/geoserver/geoserver/blob/f33bd705a0aba17230f6e9f25982f0b484f93e60/src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java#L934

2021-03-23 10:05 UTC, taba90 commented
thanks for your review @aaime  your feedback have been applied

2021-03-23 16:06 UTC, aaime approved these changes
Much better, thanks!

2021-03-23 16:07 UTC, merged