[GEOS-10030] SLDService add a checks on max unique values for uniqueInterval classification vector data
geoserver/geoserver pull request #4990
Opened 2021-04-20 08:02 UTC by taba90

blocked by https://github.com/geotools/geotools/pull/3467
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

2021-04-23 14:00 UTC, aaime requested changes

2021-04-23 14:01 UTC, aaime commented on doc/en/user/source/extensions/sldservice/index.rst
> +     - -1
Actually the two work in a distinct fashion... the value provided by the user is enforced, but the internal limit controlled by the system variable is checked first, regardless of that value was provided in the request.

2021-04-26 09:37 UTC, taba90 commented on src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
> +        return result;
fixed

2021-04-26 09:38 UTC, taba90 commented
thanks for your review @aaime fixed have been applied

2021-04-26 10:53 UTC, merged