[GEOS-10116] authkey: Resolve REST role service config from environment
geoserver/geoserver pull request #5113
Opened 2021-06-16 14:20 UTC by rcoup

[GEOS-9198] (#3477) added  support for resolving env parameters in the authkey module configuration, but not for the REST role service. 

This extends support for resolving parameters in the following `GeoServerRESTRoleServiceConfig` properties:

* `baseUrl`
* `authApiKey`

## Checklist

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [X] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [X] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [X] PR for bug fixes and small new features are presented as a single commit
- [X] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [X] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [X] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] ~Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)~
- [ ] ~Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.~

2021-06-21 10:34 UTC, afabiani requested changes
I really don't think this will be sufficient to achieve what stated into the ticket.

You will need to allow the GeoServerRESTRoleService class to resolve the values too, otherwise it will keep continue using the parametrized ones.

Moreover, why only two values have been parametrized?

2021-06-29 11:14 UTC, rcoup commented
> Moreover, why only two values have been parametrized?

AFAIK the main point of environment parameterisation is the properties that are dependent on the deployment? (that seemed to be the case for some other examples I saw when investigating). For my case, the URLs point to different services in different environments, but the other configuration of the module (paths, role names, etc) is the same. Encouraging `$` in environment variables seems a little fraught, but I can certainly add it... Note that the cache variables aren't able to be set via the UI atm.

> I really don't think this will be sufficient to achieve what stated into the ticket. You will need to allow the GeoServerRESTRoleService class to resolve the values too, otherwise it will keep continue using the parametrized ones.

Has worked in my testing... other uses of GeoServerEnvironment wrt Config classes don't seem to re-resolve it?

2021-06-29 11:14 UTC, rcoup commented
Ah. Maybe you mean if the user updates the URL in the web UI to a new parameterised value? I haven't explicitly checked that, will do that now.

2021-07-20 17:28 UTC, rcoup commented
@afabiani I've rearranged it if you could please take another look? 😃

2021-09-20 09:06 UTC, afabiani approved these changes

2021-09-20 09:10 UTC, merged