[GEOS-10184] VSI Virtual File System support
geoserver/geoserver pull request #5206
Opened 2021-08-09 00:06 UTC by mtnorthcott

PR that adds a new community extension that provides [Virtual File System](https://gdal.org/user/virtual_file_systems.html) support as a datastore type. This extension supports all drivers outlined in this document and leverages the existing VRT reader for persistence. Docs have been included as reference for how to configure connection parameters (also identical to GDAL's) as this is done via a `vsi.properties` file. When configuring the data store itself, this only requires on a valid driver-prefixed path readable by GDAL once the configuration parameters stored within the aforementioned config are applied.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [x] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal)

2021-08-17 14:56 UTC, dromagnoli requested changes
First of all, thanks for the contribution, @mtnorthcott.
Then, I have a couple of questions to better understand the structure:

In general (see other plugins) we have the low level access code in GeoTools as plugin or unsupported module (when relatively young) and the GeoServer counterpart on GeoServer eventually adding the plugin as dependency and/or defining web parts for that (i.e. panels and config UI).
So we usually have formats, readers, factories in GeoTools being used by GeoServer classes or being added to the class path from GeoServer plugins/community modules.

Is there any specific reason to have all the code contained in the community module without the usual separation (GT + GS) ? 
Does this VSI plugin needs the GDAL binaries to work as the other already existing ones or is it a slightly different kind of GDAL plugin?  

I'm wondering if we could add the low-level things to the current GDAL plugin and the enabling part/panels to GeoServer.
Note that I'm not against the current code organization. I'm just trying to better understand it :)

2021-08-17 14:56 UTC, dromagnoli commented on src/community/vsi/src/main/java/org/geoserver/vsi/VSIProperties.java
> +        try {
you may want to use try-with-resources since FileInputStream implements AutoCloseable

2021-08-20 01:14 UTC, mtnorthcott commented on src/community/vsi/src/main/java/org/geoserver/vsi/VRTFile.java
> +            dataset.delete();
Good call. I've wrapped the exception throwing blocks in a try-catch-finally statement as a fix.

2021-08-20 01:15 UTC, mtnorthcott commented on src/community/vsi/pom.xml
> +    <repositories>
Was an oversight as I was building as a standalone repo. Fixed, thanks.

2021-12-08 13:02 UTC, closed without merging