[GEOS-10356] Allow feature type customization
geoserver/geoserver pull request #5587
Opened 2022-01-14 17:47 UTC by aaime

See ticket as well as [GSIP-2017](https://github.com/geoserver/geoserver/wiki/GSIP-207)

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-01-17 10:25 UTC, taba90 requested changes
Overall looks good. Found a typo in documentation and few points in code that needs clarification or modification. I've also done some manual tests and the new functionality works fine.

2022-01-17 10:37 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/impl/AttributeTypeInfoImpl.java
> +                // even if parseable, dots should be escaped
Good catch!

2022-01-17 10:48 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/RetypeFeatureTypeCallback.java
> +            throws IOException {
It was intended, but eventually, I've changed direction and it's no longer needed. Removing it.

2022-01-18 13:53 UTC, taba90 approved these changes

2022-01-18 13:59 UTC, merged