[GEOS-10332]-GrowableInternationalStringConverter can cause random XStream conversion failures
geoserver/geoserver pull request #5599
Opened 2022-01-20 10:43 UTC by yashwanthanands

[![GEOS-10332](https://badgen.net/badge/JIRA/GEOS-10332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10332)

Growable International String and Simple International String conversion failure in XStreamPersister has been fixed.

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-01-21 16:02 UTC, taba90 requested changes

2022-01-21 16:02 UTC, taba90 commented on src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
> +                writer.endNode();
I'm a bit confused here: in the closed pr you were using the Locale.getDefault() to start the node. But now you swithced to the DEFAULT_LOCALE constant. Why this change? Note that the DEFAULT_LOCALE would result in an xml element name <default>. It seems to me that the Locale.getDefault() is the preferred option here.

2022-01-21 16:02 UTC, taba90 commented on src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
> +        assertEquals(message, toTest.toString());
Doesn't have that match sense to test the equality between the String and the InternationalString value here.
What I would test instead is the byte output stream content that contains the expected string value after the persister.save method has been executed.

2022-01-24 11:18 UTC, yashwanthanands commented
@taba90

I have applied the changes given in the review feedback.

2022-01-26 12:05 UTC, taba90 approved these changes

2022-01-26 12:06 UTC, taba90 commented
seems good to me. Merging

2022-01-26 12:07 UTC, merged