[GEOS-10357]-WFS 2.0 expects namespace request parameter instead of namespaces
geoserver/geoserver pull request #5602
Opened 2022-01-21 11:09 UTC by yashwanthanands

[![GEOS-10357](https://badgen.net/badge/JIRA/GEOS-10357/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10357)

WFS 2.0 GetFeature Request allows namespace and namespaces.But it allows only namespaces for STRICT Compliance enabled.

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-01-21 16:11 UTC, taba90 requested changes
Builds are failing on gs-wfs. A test for the exception being thrown when cite compliant mode is activate is needed.

2022-01-21 16:11 UTC, taba90 commented on src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java
> +                        namespaces = null;
Why this is set to null here? Not sure this is the correct way to go.

2022-01-24 08:08 UTC, yashwanthanands commented
@taba90 

I have applied the changes given in the review feedback.

2022-01-24 09:47 UTC, nmco commented on src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java
> +            } else if ((namespaces.getURI(prefix) != null) && (qName.getNamespaceURI() != null)) {
This change is unexpected for me, looks to me that GeoServer is trying to find in the provided namespaces a URI that matches the feature type prefix that was used in the request. For example:
```
typeNames=topp:states
namespaces=xmlns(topp,http://www.openplans.org/topp),xmlns(ns2,http://someserver.example.com/ns2)
```

... in this case he should match the ``topp`` prefix with the URI ``xmlns(topp,http://www.openplans.org/topp)``.

2022-03-14 16:23 UTC, closed without merging