Set type Number for numeric properties instead of value's class (Doub…
geoserver/geoserver pull request #5661
Opened 2022-02-10 11:41 UTC by Sylad-80

…le, Integer, ...)

  

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-02-15 13:39 UTC, taba90 requested changes
Please double check my comment below. I would try to see if removing the if statement linked in the comment below fix the issue avoiding  that additional check at attribute type building time, to not limit the support for different types in attributes with same name accross documents.

Aside, this is a community module so a test for the pr is not mandatory, but It would be nice  if you could add one. 
In case you are willing to provide a test this is how you could do:
- run mvn clean install from the schemaless-features community module. It will create for you a **schemaless-mongo.properties.example** file in the` .geoserver` folder inside your User folder on your machine.
- put a valid connection string to the property value inside the file eg. `mongodb://localhost:27017` and remove the ` .example` from the file name.
- rerun the mvn clean install, now the tests should create test data on you mongodb instance and run.
- data being inserted in the test mongo db instance is [here](https://github.com/geoserver/geoserver/tree/2994d5f1cf5fa3f216f29032f34f1e66bcb358ff/src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/json) and WFS GetFeature tests are [here](https://github.com/geoserver/geoserver/blob/2994d5f1cf5fa3f216f29032f34f1e66bcb358ff/src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java#L26).

2022-02-25 09:37 UTC, Sylad-80 commented on src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/SchemalessFeatureMapper.java
> +                    .binding(value instanceof Number ? Number.class : value.getClass())
It works if we remove the conversion

2022-03-03 10:51 UTC, taba90 approved these changes

2022-03-03 10:52 UTC, taba90 commented
Looks good to me. Merging

2022-03-03 10:53 UTC, merged