[GEOS-10440] Documentation updates to reflect changes to the Elasticsearch module …
geoserver/geoserver pull request #5774
Opened 2022-04-02 16:12 UTC by turingtestfail

…in GeoTools

removed editor file

  

# Checklist

- [ x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x ] Bug fixes and small new features are presented as a single commit.
- [x ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-04-05 16:55 UTC, aaime requested changes

2022-04-05 16:55 UTC, aaime commented on doc/en/user/source/community/elasticsearch/index.rst
> +Elasticsearch aggregations are supported through WMS requests by by including the query in WMS requests through a custom rendering transformation, ``vec:GeoHashGrid``, which translates aggregation re
"requests by by including".

Bye bye! :-D

2022-04-05 16:55 UTC, aaime commented on doc/en/user/source/community/elasticsearch/index.rst
> +			         <ogc:Function name="parameter">
Formatting is not aligned here,

2022-04-05 17:31 UTC, turingtestfail commented on doc/en/user/source/community/elasticsearch/index.rst
> +Elasticsearch aggregations are supported through WMS requests by by including the query in WMS requests through a custom rendering transformation, ``vec:GeoHashGrid``, which translates aggregation re
Fixed

2022-04-05 17:32 UTC, turingtestfail commented on doc/en/user/source/community/elasticsearch/index.rst
> +			         <ogc:Function name="parameter">
Fixed

2022-04-08 16:53 UTC, aaime approved these changes

2022-04-09 09:37 UTC, merged