[GEOS-10495] Request Logger Memory Buffer Limits
geoserver/geoserver pull request #5888
Opened 2022-05-23 02:15 UTC by turingtestfail

Added unit tests

documentation

cleanup

cleanup 2

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-05-23 12:25 UTC, aaime requested changes
Looks good, see feedback below.

2022-05-23 19:01 UTC, turingtestfail commented on doc/en/user/source/configuration/globalsettings.rst
> -.. _config_globalsettings_log_buffer:
fixed

2022-05-23 19:01 UTC, turingtestfail commented on doc/en/user/source/configuration/globalsettings.rst
> +* :guilabel:`Number of characters to log for incoming POST requests`: In more verbose logging levels, GeoServer will log the body of XML (and other text formats) recieved by ``POST`` and ``PUT`` requ
fixed

2022-05-23 19:01 UTC, turingtestfail commented on src/main/src/main/java/org/geoserver/filters/LoggingFilter.java
> +            // compatibility
fixed

2022-05-23 19:01 UTC, turingtestfail commented on src/main/src/main/java/org/geoserver/filters/LoggingFilter.java
> +                        && requestLogBufferSize > 0
fixed

2022-05-23 19:02 UTC, turingtestfail commented on src/main/src/test/java/org/geoserver/filters/LoggingFilterTest.java
> +                getLog("false", "true", "true", LoggingFilter.REQUEST_LOG_BUFFER_SIZE_DEFAULT);
fixed

2022-05-24 10:25 UTC, aaime approved these changes

2022-05-24 10:25 UTC, merged