[GEOS-10505] Display style format as new column in Styles-list, along with Style Name and Workspace
geoserver/geoserver pull request #5894
Opened 2022-05-25 14:19 UTC by mmohiahmed

[![GEOS-10505](https://badgen.net/badge/JIRA/GEOS-10505/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10505)

It's beneficial for our company (and hopefully other users), to add a new column 'Format' in Data > Styles table along with 'Name' and 'Workspace'. Formats will be SLD, ZIP, Property etc. Will you accept this as my first OSS contribution?
# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [X] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [X] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [X] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-05-25 15:29 UTC, petersmythe commented
@aaime @jodygarnett or other core developers, please take the time to review my AfriGIS colleague's PR.  We're trying to build up some internal developer capacity to tackle small changes, and hopefully more in time.  Thanks, Peter

2022-05-30 06:28 UTC, jodygarnett commented
@petersmythe I thought I had already provided feedback, here is a doc failure, and I am not sure how to add a test case to this one. Perhaps copy one of the other examples and confirm that the format is visible on screen?

2022-05-30 10:01 UTC, aaime commented
Should not be merged without a test. 

In order to add a test:
* Extend the existing StylePageTest
* Add one SLD 1.1 style (to have something different)
* Start StylePage, check the column is there and has the right contents (see the testWorkspaceFilter method for inspiration, you could have the style names set up so that only one style shows at a time, and check the SLD 1.0 and SLD 1.1 cases one by one.)

2022-05-30 10:53 UTC, aaime requested changes

2022-05-30 10:53 UTC, aaime commented on src/web/core/src/main/java/org/geoserver/web/wicket/StyleFormatLabel.java
> +                                .toString();
[No need for StringBuilder for simple concatenation](https://dzone.com/articles/string-concatenation-performacne-improvement-in-ja). Use it in loops or string builds spanning several lines, but here it's overkill and harder to read.

```suggestion
                        new formatDisplayName + " " + versionString;
```

2022-05-30 10:53 UTC, aaime commented on src/web/wms/src/main/java/org/geoserver/wms/web/data/StylePage.java
> +                                    Version formatVersion =
Setting up the label is split among the code here and the decated StyleFormatLabel component. Please move everything inside StyleFormatLabel instead, you could give it the entire itemModel as constructor argument for example, and perform extraction and formatting in there.

2022-05-30 10:53 UTC, aaime commented on src/web/wms/src/main/java/org/geoserver/wms/web/data/StylePage.java
> +        return new StringBuilder(major.toString()).append(".").append(minor.toString()).toString();
Same as above, no need to use StringBuilder.

2022-05-31 10:32 UTC, aaime commented
Regarding the two build failures:
* The docs one is related to a new warning emitted by the latest version of Sphinx. If you rebase you branch on main (or merge) you'll get the fix required (just merged):
* The checkstyle violation is related to excessive code nesting, can normally be solved by factoring out some code bits in separate methods:

```
2022-05-30T10:42:14.9443610Z 10:42:14,943 [INFO] There is 1 error reported by Checkstyle 8.29 with /home/runner/work/geoserver/geoserver/src/../build/qa/checkstyle.xml ruleset.
2022-05-30T10:42:14.9453180Z 10:42:14,944 [ERROR] src/main/java/org/geoserver/wms/web/data/StylePage.java:[73] (regexp) RegexpSingleline: Excessive nesting found. Please try to factor out the deeply nested code in a separate method or class
```

2022-07-18 08:22 UTC, aaime commented
I've tried it locally again, found it would not display the style list anymore... this was due to some styles I have, that did not have their style handler plugged in (e..g, having CSS styles in the data dir, without the CSS plugin installed).
Before it was failing to use the styles, but would list them without issues: it's a regression, I've fixed it, merged with the latest main, and pushed the changes up. 

The build is now ongoing again, let's see if it gets to green.

2022-07-18 09:43 UTC, merged

2022-07-18 09:43 UTC, aaime commented
Cool, build was green, I've squash-merged the changes.