[GEOS-10526] Parallel REST API calls failures
geoserver/geoserver pull request #5922
Opened 2022-06-03 14:57 UTC by ahmedababnehgeo

We noticed that, in when using XML storage for roles, pressing `Remove Selected and remove role associations`, truly removes the group and role associations, but on inspecting the `roles.xml` file, we found an empty user groups tag is still there.

This can create confusion for the system administrators, since the empty tag need not be there anymore.

In this PR, we remove the `groupList` in the above-mentioned case.
  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-06-03 15:04 UTC, ahmedababnehgeo commented
relevant JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10528

2022-06-06 06:57 UTC, ahmedababnehgeo commented
@taba90 PR ready for review

2022-06-06 10:07 UTC, aaime requested changes
Looks good, minor nitpick for consistency, see below.

2022-06-06 10:07 UTC, aaime commented on src/main/src/main/java/org/geoserver/security/impl/AbstractRoleStore.java
> +        if (helper.group_roleMap.get(groupname) != null && roles != null && roles.size() == 0) {
Surprised the PMD rule on the usage of isEmpty did not catch this one, but to be consistent with the resto of the code:

```suggestion
        if (helper.group_roleMap.get(groupname) != null && roles != null && roles.isEmpty()) {
```

2022-06-13 11:16 UTC, ahmedababnehgeo commented
@aaime comment resolved

2022-06-13 12:06 UTC, merged