[GEOS-10567] Fix module modularity for OpenIdConnect
geoserver/geoserver pull request #6014
Opened 2022-06-30 06:15 UTC by ahmedababnehgeo

Refactor the OpenId Connect community module separating the `web` functionality away form the core functionality each in a separate module.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-06-30 07:39 UTC, ahmedababnehgeo commented
@taba90 PR ready for review

2022-06-30 12:25 UTC, taba90 requested changes
The splitting of the module seem fine however, I guess that at least the gs-oauth2-core module should be splitted in the same way as well.
The openid-connect profile in the gs-web-app pom.xml has not been updated remember to add the renamed dependencies to it and remove the old one.
Finally the pom in /community/release folder should be updated as well to replace the old opend id dependency the new ones.

2022-07-05 08:36 UTC, taba90 requested changes
The web parte of the oauth2 core module (oauth2/oauth2-web) has not been added as dependency in all the needed places. I've commented in some of them but not all.
The oauth2-web dependency/module needs to be present:
- in the web-app pom.xml
- in the community/release pom.xml
- in the community pom.xml (here all the profile for oauth2 related implementation have still reference to the old oauth2-core module fix them as well)
- in the pom.xml of each oauth2 implementation (google, geonode, github, openid)

2022-07-05 08:36 UTC, taba90 commented on src/community/security/oauth2/pom.xml
> +    <module>oauth2-core</module>
missing the oauth2-web module

2022-07-05 08:36 UTC, taba90 commented on src/community/pom.xml
> -        <module>security/oauth2-core</module>
missing the oauth2-web module addition

2022-07-05 08:36 UTC, taba90 commented on src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
> +
missing the dependency for the oauth2-web

2022-07-05 08:36 UTC, taba90 commented on src/community/security/oauth2/oauth2-web/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
We have the module correctly separated from the core one but is not added as a dependency where it is needed.

2022-07-06 12:06 UTC, ahmedababnehgeo commented
@taba90 PR ready for review again

2022-07-07 20:34 UTC, taba90 approved these changes

2022-07-07 20:37 UTC, merged

2022-07-15 14:52 UTC, jodygarnett commented
I am having trouble building this cleanly with -PcommunityRelease,oauth2-openid-connect:

```
[ERROR] [ERROR] Project 'org.geoserver.community.security:gs-sec-oauth2-core:2.21-90bb3fce62' is duplicated in the reactor @ 
[ERROR] Project 'org.geoserver.community.security:gs-sec-oauth2-core:2.21-90bb3fce62' is duplicated in the reactor -> [Help 1]
```

This is because the module structure is not consistent across these two profiles:

community/pom.xml profilecommunityRelease profile has:
````
        <module>security</module>
        <module>security/oauth2/oauth2-core</module>
        <module>security/oauth2/oauth2-web</module>
        <module>security/oauth2-google</module>
        <module>security/oauth2-github</module>
        <module>security/oauth2-geonode</module>
        <module>security/oauth2-openid-connect</module>
        <module>security/keycloak</module>
````

community/pom.xml profile oauth2-openid-connect:
````
        <module>security/oauth2/oauth2-core</module>
        <module>security/oauth2/oauth2-web</module>
        <module>security/oauth2-openid-connect</module>
````

community/security/pom.xml profile oauth2-openid-connect:
```
        <module>oauth2</module>
        <module>oauth2-openid-connect</module>
```