[GEOS-10587] Allow DataStore to auto disable on connection failure
geoserver/geoserver pull request #6064
Opened 2022-07-15 12:21 UTC by taba90

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-07-21 09:12 UTC, aaime requested changes
@taba90 looks like the development was cut short and some bits are missing

2022-07-21 09:12 UTC, aaime commented on doc/en/user/source/data/webadmin/stores.rst
> +* **Auto disable on connection failure** - auto disables access to the store if any issue happens when geoserver try to acquire access to the store
```suggestion
* **Auto disable on connection failure** - auto disables access to the store if any issue happens when GeoServer tries to acquire access to the store
```

2022-07-21 09:12 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/impl/StoreInfoImpl.java
> +    protected boolean disableOnConnFailure;
New field, but equals and hashCode have not been updated.

2022-07-21 09:12 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/StoreInfo.java
> +     * Get the auto disable flag on connection failure.
```suggestion
     * When true, the {@link ResourcePool} will automatically disable the store on connection failure. Defaults to false.
```

(I should have linked to the Resource

2022-07-21 09:12 UTC, aaime commented on src/main/src/main/java/org/geoserver/security/config/BaseSecurityNamedServiceConfig.java
> +                /*try {
Unrelated change, please remove.

2022-07-21 09:12 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
> +    private void disableStoreInfo(WorkspaceInfo ws, String name) {
The documentation, GUI and REST configuration work covers all types of store. And yet, the ResoucePool/ResourcePoolTest changes seem to only cover DataStore implementations, I don't see the equivalent for the other types of store.

2022-07-22 09:57 UTC, taba90 commented
@aaime thanks for the review and sorry the mess. I've pushed a branch with uncommitted changes.
Your feedback have been applied.

2022-07-22 10:02 UTC, aaime commented
Looks good, thanks. Merging!

2022-07-22 10:02 UTC, merged

2022-07-22 15:31 UTC, jodygarnett commented
I was not keen on this functionality/workflow - see comments on jira ticket.

2022-07-22 15:48 UTC, aaime commented
@jodygarnett you did not want the functionality to be merged and all you said on the ticket was:

```
I thought they already did this? Perhaps only during initial connection attempt?

So what is the user experience you are trying for here …
```

Next time try to be clearer. That said, I don't think you understand what the flag is doing, or what is the default behavior of it (it's off by default).