[GEOS-10638] drop Java 8 support from docs
geoserver/geoserver pull request #6137
Opened 2022-08-27 12:44 UTC by euanmitchell

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-08-27 12:56 UTC, jodygarnett commented
Code sprint activity; documenation rather than functional change so I am not going to require a contribution agreement.

2022-08-27 14:40 UTC, jodygarnett requested changes
A small number of whitepace changes due to text editor

2022-08-27 14:40 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
what space change due to editor

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
      Press :guilabel:`Free locks` to release all feature locks currently held by the server and update the field value to zero.
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/configuration/status.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/installation/index.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/installation/linux.rst
> +
```suggestion
   
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/installation/linux.rst
> +
```suggestion
      
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/installation/war.rst
> +
```suggestion
		
```

2022-08-27 14:58 UTC, jodygarnett commented on doc/en/user/source/installation/win_binary.rst
> +
```suggestion
      
```

2022-08-27 15:46 UTC, jodygarnett approved these changes

2022-08-27 15:46 UTC, jodygarnett commented
Cleaned up the whitespace changes and removed reference to java 8 in developers guide, looks good to me.

2022-08-27 16:16 UTC, ianturton commented
Lgtm

On Sat, 27 Aug 2022, 17:46 Jody Garnett, ***@***.***> wrote:

> Cleaned up the whitespace changes and removed reference to java 8 in
> developers guide, looks good to me.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/geoserver/geoserver/pull/6137#issuecomment-1229216296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA55IMKRI3MG6BEHGNIVXLV3IZ6JANCNFSM57ZIZFZA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-10-11 04:55 UTC, jodygarnett commented
The conflict is a new section at the end of the page, not sure why it could not figure it out.

2022-10-22 02:07 UTC, jodygarnett commented
With the proposal accepted, and the RC out this can now be merged to main

2022-10-22 02:08 UTC, merged