Add support for manual configuration of start and end value in WMS-Time
geoserver/geoserver pull request #6266
Opened 2022-10-18 14:18 UTC by weskamm

This adds two new input fields in the Dimensions Tab of a layer.
The fields allow to manually specify the start and end datetime GeoServer should use when generating the capabilities for this layer:

![image](https://user-images.githubusercontent.com/1381363/196456249-8bc0cbba-b7c1-4b6e-a31b-01bc82e08d26.png)

Values have to be ISO8601 or the string `PRESENT` to reflect the current DateTime in the Capabilities.
The settings from the screenshot above lead to the following capabilities for that layer:

![image](https://user-images.githubusercontent.com/1381363/196454863-ed7972d2-ebad-47fb-87db-e629717305d6.png)

When specifying start and end times, the automatic detection of those which GeoServer usually does is skipped and the given values are used.

This is especially useful when working with layers that are based on very large datasets, as the auto detection may become very slow / unresponding leading to slow / unresponsive capabilities responses.
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-10-19 05:06 UTC, jodygarnett commented
Q: Does the REST API need to be updated with the new fields also?

2022-10-19 09:18 UTC, weskamm commented
The two new fields are children of the `dimensionInfo` element, which is used in as an `entry` in the `metadata` set.
It seems that none of the current time configuration parameters are documented.

Anyway, i could add a snippet like
```
<featureType>
  <metadata>
    <entry key="time">
        <dimensionInfo>
            <enabled>true</enabled>
            <attribute>time</attribute>
            <presentation>DISCRETE_INTERVAL</presentation>
            <startValue>2020-05-01T00:00:00Z</startValue>
            <endValue>2021-06-01T00:00:00Z</endValue>
        </dimensionInfo>
    </entry>
  </metadata>
</featureType>
```
to the examples in `configuration.yaml` and `featuretypes.yaml` if its useful

2022-10-21 12:43 UTC, weskamm commented
Ok, i have added those snippets to the REST API docs

2022-10-24 09:15 UTC, mprins requested changes
This enhancement requires a Jira issue so it shows up in release notes etc.

2022-10-24 11:06 UTC, aaime requested changes
I was looking forward to this change, there is indeed a need for statically configured dimensions.

The implementation has significant shortcomings though.

The generic "start/ed of data range" name seems to imply it can be used for elevation and custom dimension as well, and indeed the UI allows for its configuration in both elevation:

![image](https://user-images.githubusercontent.com/325433/197508280-23f905ef-2303-4087-8174-d558c7ac1391.png)

It also breaks the ability to configure a custom vector dimension, the moment one tries to add one:

https://user-images.githubusercontent.com/325433/197509779-be7ab18a-179d-4267-b3cc-bc3a76a2e286.mp4

Exception details:

```
org.apache.wicket.WicketRuntimeException: The component(s) below failed to render. Possible reasons could be that:
	1) you have added a component in code but forgot to reference it in the markup (thus the component will never be rendered),
	2) if your components were added in a parent container then make sure the markup for the child container includes them in <wicket:extend>.

1. [WebMarkupContainer [Component id = startEndContainer, page = org.geoserver.web.data.resource.ResourceConfigurationPage, path = publishedinfo:tabs:panel:vectorCustomDimPanel:mainDiv:form:vectorCustomDimensionsView:1:vectorCustomDimension:customVectorEditor:configContainer:configs:startEndContainer, type = org.apache.wicket.markup.html.WebMarkupContainer, isVisible = true, isVersioned = false], children =  [TextField [Component id = startValue]][Component id = startValueValidationMsg][TextField [Component id = endValue]][Component id = endValueValidationMsg]]
2. [TextField [Component id = startValue, page = org.geoserver.web.data.resource.ResourceConfigurationPage, path = publishedinfo:tabs:panel:vectorCustomDimPanel:mainDiv:form:vectorCustomDimensionsView:1:vectorCustomDimension:customVectorEditor:configContainer:configs:startEndContainer:startValue, type = org.apache.wicket.markup.html.form.TextField, isVisible = true, isVersioned = false]]
3. [TextField [Component id = endValue, page = org.geoserver.web.data.resource.ResourceConfigurationPage, path = publishedinfo:tabs:panel:vectorCustomDimPanel:mainDiv:form:vectorCustomDimensionsView:1:vectorCustomDimension:customVectorEditor:configContainer:configs:startEndContainer:endValue, type = org.apache.wicket.markup.html.form.TextField, isVisible = true, isVersioned = false]]
```

I believe adding actual support for elevation be easy, please consider it. Have a look at custom dimensions too, if you really don't intend supporting it, be very clear about it in documentation and make sure the UI does not show up and trick users into entering values that will not work.

Implementation wise, it covers WMS, however, the configurations are global and there are other services dealing with dimensions, for example WCS 2.0 reports time as well (see WCSDimensionHelper). The same goes for the WMTS multidimensional extension, and for time support in OGC API.

I guess they will all carry on using queries, which may be the source for inconsistency across services (some reporting declared values, others reporting actual one).
Personally, I would not ask you to go an implement consistent support across all services, but it should be clear from documentation that the scope of these two new settings is limited to WMS and users should expect a different behavior elsewhere.
That said, it's just my opinion, I recommend discussing this topic on the developer list.

Testing is a bit limited too, can you cover WMS 1.1 and continuous interval presentation as well?

2022-10-24 12:21 UTC, aaime commented
And oh, another thing... a few months ago a colleague of mine tried to implement something similar, but based on a fixed list of values (we did not end up contributing it as the implementation was too poor).

The context was that if one has vector data with hundreds of millions of records, but relatively few unique scattered dimension values (few thousands), the call to a distinct on such dataset would have taken too much time, even on an index. So the UI allowed to enter a comma-separated list of values.

Here instead you're concentrating on start/end, which normally are pretty fast to read from an index, because they are the beginning and end of the index tree (so a few steps away from the root of the b-tree, no need to walk it all). And yet here you're trying to optimize away exactly that... wondering what's the context?
Of course not having an index would be a cause, but that would slow down every request, not just capabilities (the fix is in the database in that case). Maybe you have a lot of layers configured with start/end, and you're just trying to avoid making a lot of queries, that even if fast, would have a cost in terms of latency?

2022-11-23 13:17 UTC, weskamm commented on src/wms/src/main/java/org/geoserver/wms/capabilities/DimensionHelper.java
> +                    }
Done. Had to make the DimensionHelper public for this

2022-11-23 14:00 UTC, weskamm commented
So i have extended this to also cover elevation and custom dimensions.
Tests have been extended and now also cover WMS 1.1.1.
Please review again.

As for your question, yes, we had performance issues with lots of layers based on massive datasets, which in sum make the capabilities slow even when using indices

2022-11-23 16:08 UTC, weskamm commented
not sure why the jdk 17 check is failing, any hints?

2022-11-28 15:11 UTC, aaime requested changes
Looks quite good, thanks! Found minor issues here and there, should be quick fixes.

2022-11-28 15:11 UTC, aaime commented on src/wms/src/main/java/org/geoserver/wms/WMS.java
> +        if (!StringUtils.isEmpty(startValue) && !StringUtils.isEmpty(endValue)) {
The configuration can be changed via UI (which I see is resetting the fields contents if list presentation is chosen), but can also be modified via REST, often without full understanding of how things are supposed to work. I'd recommend adding a ``&& time.getPresentation != DimensionPresentation.LIST``, or similar condition, to make sure the presentation and configured values are compatible.

2022-11-28 15:11 UTC, aaime commented on src/wms/src/main/java/org/geoserver/wms/WMS.java
> +        if (!StringUtils.isEmpty(startValue) && !StringUtils.isEmpty(endValue)) {
Same as above.

2022-11-29 07:50 UTC, weskamm commented
fixed

2022-12-13 09:38 UTC, aaime commented
All changes look good. While checking the code a new question came to mind: how do you see this new setting play with the default value selection strategy? 

The current documentation and implementation both say the same thing: this change affects only the capabilities. If a user selected "min" or "max" as the default value, they will still be pulled from the data source, causing a protocol violation (the value declared in the caps is not the one used in GetMap). 
This can be fixed by declaring the default value also as a fixed value, repeating the value chosen in the static min/max fields. It's inconvenient, but users could be warned about it.

Is this what you expected users to do?

2022-12-13 12:07 UTC, aaime approved these changes

2022-12-14 16:10 UTC, weskamm commented
> Actually wait... the default value declared in the capabilities does not come from min/max set in the new GUI elements, or does it?

No it doesnt. Its just that what the user configures. If one chooses to set a default value outside of the static range, it will appear like that in the caps

2022-12-21 10:29 UTC, merged

2022-12-21 10:29 UTC, aaime commented
Ok, merged :-D

2023-01-10 10:54 UTC, weskamm commented
@aaime what has to be done to get a backport of this PR? Could you give me a hint on this? And if this gets backported, would it be included in the upcoming 2.22.1 Release? Thanks!

2023-01-10 10:56 UTC, aaime commented
For backport on a stable series you have to ask on the devel list, showing that if the new functionality is not used, then there is no chance of regression. Also show that it will work seamlessly with existing data directories (no requirement for changes to the config contents).