[GEOS-10762] Allow enabling auto-escaping for WMS GetFeatureInfo HTML templates
geoserver/geoserver pull request #6394
Opened 2022-11-29 20:46 UTC by sikeoka

This PR adds a WMS setting to enable/disable FreeMarker's built-in auto-escaping functionality for WMS GetFeatureInfo HTML templates.

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2022-12-05 21:08 UTC, sikeoka commented
Any thoughts about this @aaime?

2022-12-06 08:34 UTC, aaime commented
Will review next week, this Monday I had other engagements.

2022-12-12 15:04 UTC, aaime requested changes
Looks good, see comments below for minor issues.

2022-12-12 15:04 UTC, aaime commented on src/wms/src/main/java/org/geoserver/wms/WMSInfoImpl.java
> +    private boolean autoEscapeTemplateValues;
I was about to ask "what about equals/hashcode/toString"?
But it seems none of them has been implemented in WMSInfoImpl... oooh well, carry on...

2022-12-12 15:33 UTC, sikeoka commented on doc/en/user/source/services/wms/webadmin.rst
> +By default GetFeatureInfo results are printed in the HTML templates without any automatic escaping, which could result in incorrect and potentially malicious results. This behavior can be activated o
I'm not going to post the information here but I sent an email to the geoserver-security list a little over a month ago that demonstrated this against a GeoServer instance with default settings and no extensions and without requiring any administrator privileges.

2022-12-12 15:36 UTC, aaime commented on doc/en/user/source/services/wms/webadmin.rst
> +By default GetFeatureInfo results are printed in the HTML templates without any automatic escaping, which could result in incorrect and potentially malicious results. This behavior can be activated o
Ah, I never saw the mail. Read it now.

2022-12-12 15:36 UTC, aaime approved these changes

2022-12-12 15:36 UTC, merged