[GEOS-10837] geopackage output fails when java.io.tmpdir on network share
geoserver/geoserver pull request #6607
Opened 2023-02-15 20:47 UTC by davidblasby

This allows the user to set a property (i.e. `-Dgeopackage.getfeatureoutput.tempdir=/path/to/temp`) that uses an alternative temp dir for the geopackage.  For people with the standard java temp dir being a mounted network drive, they should use this (pointing to a local drive).

GeoPKG (SQL Lite) has a lot of problems locking when writing to cloud (or network-mounted) file systems.

NOTE: I moved the test cases into the "proper" package (to match the class-under-test `GeoPackageGetFeatureOutputFormat`).
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [n/a] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [n/a] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-02-15 21:08 UTC, jodygarnett commented on src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java
> +            throw new IOException(
```suggestion
            throw new FileNotFoundException(
```

Will need to adjust import also

2023-02-15 21:13 UTC, jodygarnett commented on src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java
> +     * @return
```suggestion
     * @param prefix filename prefix, must be three characters or more
     * @param suffix filename suffix, or if null {@code null} suffix {@code ".tmp") used
     * @return path to newly created temporary file
```

2023-02-16 06:04 UTC, mprins commented
I'd rather use `java.io.tmpdir` or  `CATALINA_TMPDIR` instead of adding a property that only fixes this for one format.

2023-02-16 07:13 UTC, jodygarnett commented
> I'd rather use `java.io.tmpdir` or `CATALINA_TMPDIR` instead of adding a property that only fixes this for one format.

This is explicitly to avoid a ``java.io.tmpdir`` setting which as been set to a network drive. Apparently that is an acceptable approach when running some kind of docker image with hardly any local disk.

This approach is somewhat similar to how WPS has a resource storage directory.

2023-02-16 13:46 UTC, mprins commented
OK, I knew it had to be something exotic 😺

2023-04-13 00:30 UTC, jodygarnett commented
@davidblasby I am taking this out of draft. The change you have done looks clean; and I do understand why it is required. I am going to add a note for the documentation (which is my only feedback).

2023-04-13 00:32 UTC, jodygarnett requested changes
Only useful feedback is to add a note to the docs which I will do now before merge and backport. Thank you for the improvement.

2023-04-14 22:30 UTC, merged