NWC-RDT-120 - Importer, add a flag to avoid removal of other geometri…
geoserver/geoserver pull request #6626
Opened 2023-02-23 13:15 UTC by Judge73

NWC-RDT-120 - Importer, add a flag to avoid removal of other geometries when creating a point from lat/lon. Make sure the geometry name is configurable while at it.

Added support of pointFieldName to [ImportJSONReader](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONReader.java#L350)/[Writer](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONWriter.java#L470) to set if from REST API calls. 
Also added preserveGeometry flag to prevent [AttributesToPointGeometryTransform](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java#L67) deletion of geometry when needed.
Added tests that check if transform request with new fields behaves correctly to [ImporterIntegrationTest](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java#L321) and that new fields are represented correctly when requesting info about transform to [AttributesToPointGeometryTransformTest](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/AttributesToPointGeometryTransformTest.java#L24)

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-02-23 15:46 UTC, mprins commented
please run `mvn spotless:apply` before commit/push so we're not bothered with formatting problems

2023-02-23 16:38 UTC, aaime commented
@Judge73 is actually using spotless, but AFAIK fighting with Windows, newlines and git settings. As a Linux user I can help only so much.

2023-02-24 12:01 UTC, aaime requested changes
Looks good in general, see small change requests below.
I've tested it interactively with a couple of imports, works as expected :+1:

2023-02-27 10:18 UTC, Judge73 commented on src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java
> +            builder.remove(lngField);
done

2023-02-27 14:41 UTC, aaime approved these changes

2023-02-27 14:41 UTC, merged