Force use of AntRun plugin 3.1.0
geoserver/geoserver pull request #6630
Opened 2023-02-24 15:18 UTC by jusabatier

This PR force the use of the 3.1.0 version of AntRun plugin.

As in last version <tasks> were replaced with <task>, if we don't force the version it use the old 1.3 that doesn't support <tasks>. 

It results for example in @project.version@ not replaced in some web/core properties files.

2023-02-25 00:35 UTC, bradh commented
Instead of duplicating the version number, can you use a property, or even better, put it in managed dependencies?

2023-02-25 10:25 UTC, mprins requested changes
Please add the m-a-p with version  to the pluginManagement section of the parent pom file and remove the version element from any m-a-p in build sections

2023-02-25 16:34 UTC, mprins commented
should fix [GEOS-10871](https://osgeo-org.atlassian.net/browse/GEOS-10871)

2023-02-25 16:43 UTC, jodygarnett commented
When’s e get this sorted I will cherry-pick the change against the 2.22.2 and redeploy.

2023-02-27 06:28 UTC, jodygarnett commented
Okay I noticed this was branching from 2.22.x rather than ``main``. Going to cherry pick the commit and clean things up. Thanks for getting this activity started!

2023-02-27 07:03 UTC, jodygarnett commented
Please see https://github.com/geoserver/geoserver/pull/6635 for PR against ``main``. I also amended your commit to follow our naming convention which helps when back porting.

2023-02-27 07:03 UTC, closed without merging