[GEOS-10929] isolated workspace may cause broken links between catalo…
geoserver/geoserver pull request #6832
Opened 2023-05-08 10:11 UTC by NielsCharlier

…g objects

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-05-22 10:46 UTC, aaime requested changes

2023-05-22 10:46 UTC, aaime commented on src/community/wps-sextante/src/main/java/org/geoserver/wps/sextante/GTVectorLayer.java
> +import org.geotools.util.logging.Logging;
What's happening here? Unrelated reformats here and in a few other files.

2023-05-22 10:46 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
> +        rawFacade = facade;
So the actual important change is here... the refactor of the event management obfuscates it (still a good thing, but it's a distraction when trying to find what makes the fix actually work).

2023-05-22 10:46 UTC, aaime commented on src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
> +    public CatalogImpl getRawCatalog() {
Bit of Javadoc with an explanation of why the original CatalogImpl is not "raw"?

2023-05-25 07:14 UTC, NielsCharlier commented
@aaime thanks for the review, made the changes

2023-05-25 15:42 UTC, merged