[GEOS-10856] geoserver monitor plugin - scaling troubles
geoserver/geoserver pull request #6986
Opened 2023-07-05 09:34 UTC by hyperman2

[![GEOS-10856](https://badgen.net/badge/JIRA/GEOS-10856/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10856)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-07-17 13:15 UTC, aaime requested changes
Looks good in general, see comments below.

2023-07-17 13:15 UTC, aaime commented on doc/en/user/source/extensions/monitoring/configuration.rst
> +You can choose the number of post processor threads by configuring the ``postprocessorthreads``
```suggestion
You can choose the number of post processor threads by configuring the ``postProcessorThreads``
```

The file is using camelCase for all other properties.

2023-07-17 13:15 UTC, aaime commented on doc/en/user/source/extensions/monitoring/configuration.rst
> +by configuring the ``dnscacheconfiguration`` property in the ``monitor.properties`` file.
Same as above

```suggestion
by configuring the ``dnsCacheConfiguration`` property in the ``monitor.properties`` file.
```

2023-07-17 13:35 UTC, hyperman2 commented on src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorConfig.java
> +    static final String DNS_CACHE_DEFAULT = "expireAfterWrite=15m";
Thanks, I'll look at this in the evening

Regarding DNS_CACHE_DEFAULT: I see a few options:  
1) Change to "expireAfterWrite=15m,softValues" should provide the same behaviour as soft references.
2) Change to "expireAfterWrite=15m,maximumSize=100" should provide the same maximum as in the current code.  

As the current code only reads the cache, never writes it, the current cache is always empty, so I can't look at what happens right now.    I presume soft refs are more heavy on the GC as they need special handling, and the cost of a String is very low, so I propose option 2, maybe even raising the maximum to 1000.

2023-08-01 08:34 UTC, hyperman2 commented
Sorry, didn't see the 'Request re-review button'.  All remarks have been adapted

2023-08-18 10:43 UTC, aaime approved these changes

2023-08-18 10:43 UTC, merged

2023-08-18 11:37 UTC, hyperman2 commented
Thank you very much