[GEOS-11101] metadata: multiple tabs
geoserver/geoserver pull request #7073
Opened 2023-08-14 06:12 UTC by NielsCharlier

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-08-18 10:38 UTC, aaime commented
As a supported module, new functionality should come with documentation updates.

2023-09-11 10:48 UTC, NielsCharlier commented
is this okay to merge?

2023-10-07 09:50 UTC, aaime requested changes

2023-10-07 09:50 UTC, aaime commented on doc/en/user/source/extensions/metadata/uiconfiguration.rst
> +
A screenshot showing how multiple tabs are rendered in the UI would not hurt

2023-10-07 09:50 UTC, aaime commented on src/extension/metadata/src/test/java/org/geoserver/metadata/AbstractMetadataTest.java
> +/* (c) 2018 Open Source Geospatial Foundat-ion - all rights reserved
Nope

2023-10-30 10:00 UTC, merged