Add section about logging configuration hardening
geoserver/geoserver pull request #7144
Opened 2023-10-01 16:53 UTC by anthares101

The idea is to add a little section to the documentation that can help users ensure the logging configuration is not missconfigured with neferious intentions even with administration access.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-10-01 20:27 UTC, mprins requested changes
Several typos and syntax error. This is not a markdown file.
Also I think it's poor and incomplete advice

2023-10-01 21:17 UTC, anthares101 commented
> Several typos and syntax error. This is not a markdown file. Also I think it's poor and incomplete advice

Sorry about the typos not english native speaker, I tried to fix both the typos and the syntax problem (I hope, did not use this format before). 

About the poor advice, the idea until the security advisory is published is to keep this vague. I can add more about the impact of the log configuration but I dont want to disclouse anything non public.

2023-10-02 10:48 UTC, aaime commented
Idea for rewording:

```
For production systems, it is advised to set the log location via the environment variable. This prevents overriding it via the administration GUI or REST API, providing better separation of responsibility between those setting up and controlling the actual machine, and those configuring the GeoServer data, styles and the like.  Follow :ref:`overriding_the_log_location_setup_in_the_geoserver_configuration` for more information
```

2023-10-02 16:01 UTC, anthares101 commented
Thanks for the help @aaime 😄

2023-10-03 22:53 UTC, jodygarnett commented on doc/en/user/source/production/config.rst
> +
Thanks, that is clearly written.

There are actually several ways (environmental variable, java system property, or web application parameter) to set these things. I know most system admins would just use the environmental variable, but there may still be someone configuring web application parameters in tomcat (hint I am that someone).

aside: I believe there are a number of settings that can be defined in this manner that all could be used if one wished to enforce a strong separation of concerns between those running the machine and the REST / GUI interface.

2023-10-03 23:19 UTC, jodygarnett commented on doc/en/user/source/production/config.rst
> +For production systems, it is advised to set the log location via the environment variable. This prevents overriding it via the administration GUI or REST API, providing better separation of responsi
```suggestion
For production systems, it is advised to define the log location using the ``GEOSERVER_LOG_LOCATION `` parameter (defined as either an environment variable, java system property, or servlet context parameter.)

Defining ``GEOSERVER_LOG_LOCATION`` has priority, causing the value provided using the Admin Console GUI or REST API to be ignored. This apporach establishes a separation of responsibility between those setting up and controlling the actual machine, and those configuring the GeoServer application.

Follow :ref:`overriding_the_log_location_setup_in_the_geoserver_configuration` for more information
```

2023-10-03 23:22 UTC, jodygarnett requested changes
I provided a clarification and broke your statement into smaller sentences.

For some reason the phrase "This prevents overriding" sounded awkward to me. It is more that the GEOSERVER_LOG_LOCATION has priority, or establishes the default value. 

You can consider the proposed changes and let me know what you think :)

I also looked if there was any other settings that could be handled in this manner, ``PROXY_BASE_URL`` was the only one that works in a similar fashion.

2023-10-04 12:54 UTC, anthares101 commented
@jodygarnett looking good, proposed changes applied 😄

2023-10-05 05:36 UTC, jodygarnett commented
Got build failure:

05:11:06,747 [INFO]      [exec] /home/runner/work/geoserver/geoserver/doc/en/user/source/production/config.rst:16: WARNING: Inline literal start-string without end-string.
05:11:25,374 [INFO]      [exec] /home/runner/work/geoserver/geoserver/doc/en/user/source/production/config.rst:20: WARNING: undefined label: 'overriding_the_log_location_setup_in_the_geoserver_configuration'

2023-10-05 11:00 UTC, mprins requested changes
there is a build failure on this change:

```
05:11:06,747 [INFO]      [exec] /home/runner/work/geoserver/geoserver/doc/en/user/source/production/config.rst:16: WARNING: Inline literal start-string without end-string.
05:11:25,374 [INFO]      [exec] /home/runner/work/geoserver/geoserver/doc/en/user/source/production/config.rst:20: WARNING: undefined label: 'overriding_the_log_location_setup_in_the_geoserver_configuration'
```

2023-10-09 02:16 UTC, bradh commented on doc/en/user/source/production/config.rst
> +Defining ``GEOSERVER_LOG_LOCATION`` has priority, causing the value provided using the Admin Console GUI or REST API to be ignored. This apporach establishes a separation of responsibility between th
```suggestion
Defining ``GEOSERVER_LOG_LOCATION`` has priority, causing the value provided using the Admin Console GUI or REST API to be ignored. This approach establishes a separation of responsibility between those setting up and controlling the actual machine, and those configuring the GeoServer application.
```

2023-10-09 08:08 UTC, jodygarnett commented on doc/en/user/source/production/config.rst
> +Follow :ref:`overriding_the_log_location_setup_in_the_geoserver_configuration` for more information.
```suggestion
Follow :ref:`Overriding the log location <logging>` for more information.
```

2023-10-09 08:19 UTC, jodygarnett commented
Build failure fixed, we are good to go. Thanks for working on this everyone.

2023-10-09 08:21 UTC, merged