GEOS-11150 add geoserver-monitor-kafka extension
geoserver/geoserver pull request #7171
Opened 2023-10-09 11:36 UTC by spike83

If we want to analyze the data produced by the monitoring extension we had the option to write to a database using hibernate. Going forward I’d like also to be able to stream the monitoring data into a Kafka topic.

With stream processing we can build the aggregates we want e.g. with KsqlDB, Flink or Kafka Streams Application and provide reports in near real time… But foundation is to have the data streamed into a topic…

With this extension we can stream the data into a Kafka topic and configure all the producer options as we want to.
  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-11-06 10:20 UTC, aaime commented
Whoops, looks like it has accumulated conflicts. Personally I have no experience with Kafka, cannot review the details, but the direction looks like a good one to me. Anyone else that wants to have a look before merge?

2023-11-06 13:12 UTC, mprins requested changes
I've provided some small changes to the pom files.

Aside there seems to be Kafka 3.6.0; but since I haven't used kafka I'm not sure if using that is opportune (compared to 3.5.1)

2023-11-06 13:12 UTC, mprins commented on src/community/pom.xml
> +            <version>3.2.0</version>
this version is already provided through pluginManagment of the parent pom:
https://github.com/geoserver/geoserver/blob/f5355bc54f1a09b2c429406002dddd09f2f5fac3/src/pom.xml#L1699-L1702

```suggestion
```

2023-11-06 13:12 UTC, mprins commented on src/web/app/pom.xml
> +          <version>2.25-SNAPSHOT</version>
```suggestion
          <version>${project.version}</version>
```

2023-11-07 06:13 UTC, spike83 commented
@mprins thanks for your review. I updated the deps. Kafka 3.6.0 was released in the mean time. Not critical but for sure a good idea to update.

2023-11-07 09:15 UTC, mprins approved these changes

2023-11-20 11:48 UTC, merged

2023-11-20 11:49 UTC, aaime commented
Merged! If you want to backport, that will have to be a manual PR, as you'll need a different version number in the pom.xml file (and potentially, I have not checked, some different API in GeoTools, if you want to go down to 2.23.x).