preauth filter - clears the security context if user changed [GEOS-11235]
geoserver/geoserver pull request #7326
Opened 2023-12-15 15:40 UTC by pmauduit

or if no preauth headers are provided anymore.

See https://osgeo-org.atlassian.net/browse/GEOS-11235 for more details.

Without this change, we can end up with a persisting session across logout.

Tests: adding utests specific to this change. Runtime tested into a docker composition.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2023-12-15 15:41 UTC, pmauduit commented
force-pushed to comply with the checklist, regarding commit naming

2023-12-18 11:09 UTC, aaime requested changes
Looks like a reasonable change to me. @afabiani could you also have a quick look?

@pmauduit mind the PMD failure, below, in the comments.

2023-12-18 11:09 UTC, aaime commented on src/main/src/test/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilterTest.java
> +                        .equals("testuser"));
This line fails over PMD checks:

```
2023-12-15T15:44:54.9213748Z 15:44:54,913 [INFO] PMD Failure: org.geoserver.security.filter.GeoServerRequestHeaderAuthenticationFilterTest:45 Rule:SimplifiableTestAssertion Priority:3 Assertion may be simplified using assertEquals.
```

Indeed it should be something like


```suggestion
        assertEquals("testuser"
                SecurityContextHolder.getContext()
                        .getAuthentication()
                        .getPrincipal()
                        .toString());
```

2023-12-18 12:37 UTC, pmauduit commented
> @pmauduit mind the PMD failure, below, in the comments.

amend-commited / force pushed to take this into account.

2023-12-21 13:54 UTC, groldan commented
The [failed build job for Java11](https://github.com/geoserver/geoserver/actions/runs/7248149616/job/19849646700?pr=7326) is unrelated. 
I've seen this happening sporadically after building the community modules:

```
Error: 2,707 [ERROR] Could not acquire lock(s)
Error: 2,707 [ERROR] java.lang.IllegalStateException: Could not acquire lock(s)
Error: 2,707 [ERROR] 
Error: 2,707 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Error: 2,707 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
Error: Process completed with exit code 1.
```

2023-12-21 14:07 UTC, aaime approved these changes

2023-12-21 14:09 UTC, aaime commented
Thanks for fixing the PMD issue. For an actual review of the contents, let's hear from @afabiani

2023-12-22 08:00 UTC, afabiani approved these changes

2023-12-27 14:24 UTC, merged