[GEOS-11305] Add layer information in the models backing STAC
geoserver/geoserver pull request #7427
Opened 2024-02-16 17:13 UTC by aaime

See ticket for details.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2024-02-19 23:21 UTC, turingtestfail requested changes

2024-02-19 23:21 UTC, turingtestfail commented on doc/en/user/source/community/opensearch-eo/STAC.rst
> +
It would be helpful for context to link back to the applicable STAC extension: https://github.com/stac-extensions/web-map-links

2024-02-19 23:21 UTC, turingtestfail commented on src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/ComplexFeatureBuilder.java
> +
Class and method javadoc?

2024-02-22 09:13 UTC, merged

2024-02-22 09:13 UTC, aaime commented
The backport to `2.23.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply eafdbb9251... [GEOS-11305] Add layer information in the models backing STAC
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging doc/en/user/source/community/opensearch-eo/STAC.rst
Auto-merging src/community/oseo/oseo-core/pom.xml
Auto-merging src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
CONFLICT (content): Merge conflict in src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
Auto-merging src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/CollectionLayer.java
CONFLICT (content): Merge conflict in src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/CollectionLayer.java
Auto-merging src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
Auto-merging src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
Auto-merging src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OpenSearchAccess.java
Auto-merging src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OrderedTypeBuilder.java
CONFLICT (content): Merge conflict in src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OrderedTypeBuilder.java
Auto-merging src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
CONFLICT (content): Merge conflict in src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
Auto-merging src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/CollectionsController.java
CONFLICT (content): Merge conflict in src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/CollectionsController.java
Auto-merging src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionLayerTest.java
CONFLICT (content): Merge conflict in src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionLayerTest.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.23.x 2.23.x
# Navigate to the new working tree
cd .worktrees/backport-2.23.x
# Create a new branch
git switch --create backport-7427-to-2.23.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick eafdbb9251febb53f3391248f330f4f843a6a6e0
# Push it to GitHub
git push --set-upstream origin backport-7427-to-2.23.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.23.x
```
Then, create a pull request where the `base` branch is `2.23.x` and the `compare`/`head` branch is `backport-7427-to-2.23.x`.