[GEOS-11294] MapML Add Support to WMS for Vector Representation
geoserver/geoserver pull request #7445
Opened 2024-02-27 16:31 UTC by turingtestfail

useFeatures UI test

added usefeatures to builder

Return features links

started on conversion

First pass at building features

clarify multi error

cleanup

PR comments part 1

Configuration Panel Constants

check for raster and more constants

fixed metadata tests

added getAsMapML to tests

removed alternative projection links and added feature reprojection

test issue

more test cleanup

fixed default num decimals

reprojectingfeaturecollection needs fallback CRS

if feature links, no query links

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2024-02-28 13:35 UTC, aaime requested changes
Need a bit of documentation for the new GUI option.

2024-02-29 18:53 UTC, turingtestfail commented on src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLConstants.java
> +    public static final String MAPML_FEATURE_FORMAT_OPTIONS = "mapmlfeatures:true";
It's all or nothing, the format option doesn't show up at all if features are not requested. So, mapmlfeatures:false never happens.

2024-02-29 19:13 UTC, turingtestfail commented
> Need a bit of documentation for the new GUI option.

Added

2024-02-29 19:13 UTC, turingtestfail commented on src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
> +        useFeaturesAllLayers = isAllLayersUseFeatures(layers);
Done

2024-02-29 19:13 UTC, turingtestfail commented on src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
> +    private boolean isAllLayersUseFeatures(List<RawLayer> layers) {
Done

2024-02-29 19:13 UTC, turingtestfail commented on src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
> +            useFeaturesAllLayers = false;
D'oh.  Not my finest work.  Fixed.

2024-02-29 19:13 UTC, turingtestfail commented on src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLFeaturesBuilder.java
> +        return settings.getNumDecimals();
Done

2024-03-01 11:00 UTC, merged

2024-03-01 11:00 UTC, aaime commented
The doc failure is unrelated, I've warned Jody in the PR that introduced the issue.