[GEOS-11202] Respect proxy base URL when building CAS service URL.
geoserver/geoserver pull request #7571
Opened 2024-04-23 18:55 UTC by mbosecke

The service URL built by the CAS extension now respects the proxy base URL (both the system property and the config value). I accomplished this by running the URL through ResponseUtils.buildUrl to ensure it ultimately goes through ProxifyingURLManger.

Furthermore, it also preserves the end-user's path and query parameters. This is to ensure that by the time the user is redirect back to the application from CAS, they will land on the original page they were trying to hit.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [x] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2024-04-24 07:17 UTC, mprins requested changes

2024-04-24 07:17 UTC, mprins commented on src/extension/security/cas/src/test/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilterTest.java
> + * (c) 2001 - 2013 OpenPlans
```suggestion
/* (c) 2024 Open Source Geospatial Foundation - all rights reserved
```

2024-04-27 12:52 UTC, mprins approved these changes

2024-04-27 12:52 UTC, mprins commented
please run `mvn spotless:apply` to fix formatting

2024-04-29 15:12 UTC, mbosecke commented
I've now run `mvn spotless:apply` but squashed all my commits into one single one (hope that's okay).

2024-05-14 12:18 UTC, petersmythe commented
Closing, reopening to trigger checks again

2024-05-14 13:02 UTC, merged

2024-05-14 13:08 UTC, aaime commented
The PR was merged with many failing builds:

![image](https://github.com/geoserver/geoserver/assets/325433/53c42843-dc17-497c-90bc-07926c9ab5e7)

Now, the failure is due to API changes that are unrelated:

```
Error: 6,180 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project gs-main: Compilation failure
Error: 6,180 [ERROR] /home/runner/work/geoserver/geoserver/src/main/src/test/java/org/geoserver/test/http/MockHttpClient.java:[26,8] org.geoserver.test.http.MockHttpClient is not abstract and does not override abstract method setExtraParams(java.util.Map<java.lang.String,java.lang.String>) in org.geotools.http.HTTPClient
```

Still, this failure might be masking some other problem. Next time please rebase onto main and have the checks run once more.

2024-05-14 13:16 UTC, petersmythe commented
I don't understand, sorry.  Minutes ago, there were only 10 (or 9?) checks, and they had all passed (after reopening the issue).  I don't know why it shows 10/19 checks passed now.