Jwt multi admin
geoserver/geoserver pull request #7610
Opened 2024-05-07 18:04 UTC by davidblasby

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [n/a] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [n/a] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2024-05-08 21:21 UTC, davidblasby commented
I will merge this monday if no one has any concerns.

2024-05-10 13:56 UTC, afabiani requested changes
Be careful, you are missing some `RoleSources` when evaluating the enums

![image](https://github.com/geoserver/geoserver/assets/1278021/de524fd9-8401-4c08-a1dc-450ecf44900a)

```
...
Caused by: org.apache.wicket.WicketRuntimeException: Error calling method: public org.geoserver.security.config.RoleSource org.geoserver.security.jwtheaders.filter.GeoServerJwtHeadersFilterConfig.getRoleSource() on object: BaseSecurityNamedServiceConfig [name=null, className=null, id=null]
	at org.apache.wicket.core.util.lang.PropertyResolver$MethodGetAndSet.getValue(PropertyResolver.java:940)
	at org.apache.wicket.core.util.lang.PropertyResolver$ObjectWithGetAndSet.getValue(PropertyResolver.java:439)
	at org.apache.wicket.core.util.lang.PropertyResolver.getValue(PropertyResolver.java:116)
	at org.apache.wicket.model.AbstractPropertyModel.getObject(AbstractPropertyModel.java:86)
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1646)
	... 142 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.geoserver.security.jwtheaders.filter.GeoServerJwtHeadersFilterConfig.JWTHeaderRoleSource.UserGroupService
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.geoserver.security.jwtheaders.filter.GeoServerJwtHeadersFilterConfig$JWTHeaderRoleSource.valueOf(GeoServerJwtHeadersFilterConfig.java:117)
	at org.geoserver.security.jwtheaders.filter.GeoServerJwtHeadersFilterConfig.getRoleSource(GeoServerJwtHeadersFilterConfig.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.wicket.core.util.lang.PropertyResolver$MethodGetAndSet.getValue(PropertyResolver.java:936)
	... 146 more
```

2024-05-10 13:56 UTC, afabiani commented on src/community/jwt-headers/jwt-headers-util/src/main/java/org/geoserver/security/jwtheaders/JwtConfiguration.java
> +import java.util.*;
GeoServer policies want to avoid importing the whole package but single classes instead.

2024-05-10 13:56 UTC, afabiani commented on src/community/jwt-headers/jwt-headers-util/src/main/java/org/geoserver/security/jwtheaders/JwtConfiguration.java
>  package org.geoserver.security.jwtheaders;
Missing copyright headers

2024-05-10 16:08 UTC, davidblasby commented
Thanks a lot for review, @afabiani - incorporated your changes.

2024-05-10 16:17 UTC, afabiani approved these changes

2024-05-13 16:24 UTC, merged