[GEOS-11556] Fix NPE when DiskQuotaMonitor is disabled
geoserver/geoserver pull request #7913
Opened 2024-09-27 07:42 UTC by vuilleumierc

When disabling the disk quota monitoring (environment variable GWC_DISKQUOTA_DISABLED set to true) there is a NullPointerException in the logs on shut down:

```
WARN 1 --- [ionShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'DiskQuotaStoreProvider': java.lang.NullPointerException: Cannot invoke "org.geowebcache.diskquota.QuotaStore.close()" because "this.store" is null
```

This happens because the store is set to null here https://github.com/geoserver/geoserver/blob/f23c089fb922e217c138c063b5d8aadf5391c881/src/gwc/src/main/java/org/geoserver/gwc/ConfigurableQuotaStoreProvider.java#L65 and the `destroy()` method of the parent class later tries to close it:
https://github.com/GeoWebCache/geowebcache/blob/a642c8b9cd839d2866dc174784356838b62b3b9a/geowebcache/diskquota/core/src/main/java/org/geowebcache/diskquota/QuotaStoreProvider.java#L51

Here I suggest to overload the `destroy()` method in `ConfigurableQuotaStoreProvider` to add a null check before closing the store.

I have tried adding a test for this but since `assertDoesNotThrow` is not available in JUnit 4, I am open for suggestions

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2024-09-27 13:01 UTC, groldan requested changes

2024-09-27 13:55 UTC, vuilleumierc commented on src/gwc/src/test/java/org/geoserver/gwc/GWCQuotaStoreDisabledTest.java
> +/* (c) 2014 -2024 Open Source Geospatial Foundation - all rights reserved
Sure, thank you for reviewing. Also it seems there really is a problem with the build (17, temurin, ubuntu-22.04), I am looking into it

2024-09-27 14:40 UTC, groldan commented on src/gwc/src/test/java/org/geoserver/gwc/GWCQuotaStoreDisabledTest.java
> +/* (c) 2014 -2024 Open Source Geospatial Foundation - all rights reserved
I'm pretty sure the build failure is unrelated, or at last I can't think of a reason why this change would have anything to do with app schema

2024-10-01 14:47 UTC, groldan approved these changes
LGTM

2024-10-01 14:48 UTC, merged