[GEOS-11664] Update REST security paths
geoserver/geoserver pull request #8170
Opened 2024-12-30 20:26 UTC by sikeoka

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

2025-01-20 10:35 UTC, aaime requested changes

2025-01-21 16:08 UTC, sikeoka commented on src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
> +    void migrateFrom25() throws Exception {
REST_CHAIN and GWC_REST_CHAIN are hardcoded values so an administrator can't change them anyways. Also, there is no assumption on the order. It will loop over each chain and check if it matches the old REST_CHAIN or GWC_REST_CHAIN values.

2025-01-27 09:55 UTC, aaime approved these changes

2025-01-27 10:14 UTC, merged

2025-06-18 20:55 UTC, jodygarnett commented
This applies to `security/config.xml` is a similar change needed for `rest.properties`?

2025-06-19 15:31 UTC, jodygarnett commented
@sikeoka I am noticing a possible regression associated with this change. The ``/geoserver/rest/workspaces.json`` endpoint is no longer respecting catalog mode HIDE and MIXED when configured for anonymous access:

```
# Allow public workspaces overview
/rest/workspaces.*;GET=IS_AUTHENTICATED_ANONYMOUSLY

# default
/**;GET=ADMIN
/**;POST,DELETE,PUT=ADMIN
```

My assumption is there is no easy way to determine available workspaces so the REST API endpoint is being used by a script or something.

2025-06-20 14:53 UTC, sikeoka commented
I'll take a look at that.

2025-06-23 15:17 UTC, sikeoka commented
@jodygarnett I didn't notice any problems using a 2.28.x snapshot. If there was a bug that could be reproduced with the default data directory, then it may have already been fixed. Otherwise, it's probably something more specific to your configuration and unrelated to these changes.

2025-06-23 23:47 UTC, jodygarnett commented
Huh - the configuration change required is in `rest.properties` mentioned above. While I can double check what branch I tested with, this is a non standard (but perfectly reasonable) rest security config.

2025-06-24 14:59 UTC, sikeoka commented
I tested your `rest.properties` change. I'm not sure exactly what your bugged behavior but you can test if it's a regression from this PR by just reverting the changes to `config.xml`.